apiVersion: v1
kind: Service
metadata:
  name: tg-core-service
  namespace: backend-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8080"
spec:
  selector:
    app: tg-core-service
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-server
  namespace: backend-server
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - dope.yanychoi.site
      secretName: ingress-tls-secrets
  ingressClassName: nginx
  rules:
    - host: dope.yanychoi.site
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: tg-core-service
                port:
                  number: 8080
