apiVersion: v1
kind: Service
metadata:
  name: tg-frontend-service
  namespace: web-app
spec:
  selector:
    app: tg-frontend-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app
  namespace: web-app
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - dope.yanychoi.site
      secretName: ingress-tls-secrets
  ingressClassName: nginx
  rules:
    - host: dope.yanychoi.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tg-frontend-service
                port:
                  number: 80