apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cloudbeaver
  namespace: db-manager
spec:
  selector:
    matchLabels:
      app: cloudbeaver
  serviceName: cloudbeaver-svc
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: cloudbeaver
          image: dbeaver/cloudbeaver:latest
          ports:
            - containerPort: 8978
              name: port-8978

---

apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver-svc
  namespace: db-manager
spec:
  selector:
    app: cloudbeaver
  type: ClusterIP
  ports:
    - port: 8978
      targetPort: 8978

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudbeaver-ingress
  namespace: db-manager
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /api/community/
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  tls:
    - hosts:
        - mysql.yanychoi.site
      secretName: ingress-tls-secrets
  ingressClassName: nginx
  rules:
    - host: mysql.yanychoi.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudbeaver-svc
                port:
                  number: 8978