apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: cicd
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd
  namespace: cicd
  annotations:
    # ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/issuer: "letsencrypt-prod"
spec:
  # tls:
  # - hosts:
  #   - monitor.yanychoi.site
  #   secretName: ingress-tls-secrets
  ingressClassName: nginx
  rules:
  - host: cicd.yanychoi.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080