apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elk
  template:
    metadata:
      labels:
        app: elk
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch/elasticsearch:7.6.2
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: cluster.name
              value: yany-cluster
            - name: bootstrap.memory_lock
              value: "true"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data
        - name: logstash
          image: logstash:7.6.2
          ports:
            - containerPort: 5044
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
      volumes:
        - name: elasticsearch-storage
          emptyDir: {}
        - name: logstash-config
          configMap:
            name: logstash-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: monitoring
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      grok {
        match => { "message" => "%{COMBINEDAPACHELOG}" }
      }
      date {
        match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
      }
    }
