apiVersion: v1
kind: Service
metadata:
  name: elk
  namespace: monitoring
  labels:
    app: elk
spec:
  selector:
    app: elk
  type: ClusterIP
  ports:
    - name: elasticsearch
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: logstash
      protocol: TCP
      port: 5044
      targetPort: 5044